-- MySQL Script generated by MySQL Workbench
-- Sat Oct  5 18:01:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Suscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Suscripcion` (
  `idSuscripcion` INT NOT NULL AUTO_INCREMENT,
  `Tipo` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idSuscripcion`),
  UNIQUE INDEX `idSuscripcion_UNIQUE` (`idSuscripcion` ASC) VISIBLE,
  UNIQUE INDEX `Tipo_UNIQUE` (`Tipo` ASC) VISIBLE,
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `TipoPerfil` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Suscripcion_idSuscripcion` INT NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil`),
  UNIQUE INDEX `idPerfil_UNIQUE` (`idPerfil` ASC) VISIBLE,
  UNIQUE INDEX `TipoPerfil_UNIQUE` (`TipoPerfil` ASC) VISIBLE,
  INDEX `fk_Perfil_Suscripcion1_idx` (`Suscripcion_idSuscripcion` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Perfil_Suscripcion1`
    FOREIGN KEY (`Suscripcion_idSuscripcion`)
    REFERENCES `mydb`.`Suscripcion` (`idSuscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `Nacionalidad` VARCHAR(70) NULL,
  `Nacimiento` DATE NULL,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idAutor`),
  UNIQUE INDEX `idAutor_UNIQUE` (`idAutor` ASC) VISIBLE,
  INDEX `fk_Autor_Perfil1_idx` (`Perfil_idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `mydb`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `idCategoria_UNIQUE` (`idCategoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subcategoria` (
  `idSubcategoria` INT NOT NULL,
  `Nombre` VARCHAR(80) NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idSubcategoria`),
  INDEX `fk_Subcategoria_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Subcategoria_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articulos` (
  `idArticulos` INT NOT NULL AUTO_INCREMENT,
  `Autor_idAutor` INT NOT NULL,
  `Nombre` VARCHAR(70) NOT NULL,
  `Fecha_Publicacion` DATE NOT NULL,
  `Texto` MEDIUMTEXT NOT NULL,
  `Premium` TINYINT NOT NULL,
  `Imagen` BLOB NOT NULL,
  `VecesVisita` INT NOT NULL,
  `Draft` TINYINT NOT NULL,
  `Revision` TINYINT NOT NULL,
  `Publicado` TINYINT NOT NULL,
  `Subcategoria_idSubcategoria` INT NOT NULL,
  PRIMARY KEY (`idArticulos`),
  UNIQUE INDEX `idArticulos_UNIQUE` (`idArticulos` ASC) VISIBLE,
  INDEX `fk_Articulos_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  INDEX `fk_Articulos_Subcategoria1_idx` (`Subcategoria_idSubcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Articulos_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articulos_Subcategoria1`
    FOREIGN KEY (`Subcategoria_idSubcategoria`)
    REFERENCES `mydb`.`Subcategoria` (`idSubcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Logueado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Logueado` (
  `idLogueado` INT NOT NULL AUTO_INCREMENT,
  `FechaLog` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idLogueado`),
  UNIQUE INDEX `idLogueado_UNIQUE` (`idLogueado` ASC) VISIBLE,
  INDEX `fk_Logueado_Perfil_idx` (`Perfil_idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Logueado_Perfil`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `mydb`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Moderado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Moderado` (
  `idModerado` INT NOT NULL AUTO_INCREMENT,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idModerado`),
  UNIQUE INDEX `idModerado_UNIQUE` (`idModerado` ASC) VISIBLE,
  INDEX `fk_Moderado_Perfil1_idx` (`Perfil_idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Moderado_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `mydb`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  UNIQUE INDEX `idAdministrador_UNIQUE` (`idAdministrador` ASC) VISIBLE,
  INDEX `fk_Administrador_Perfil1_idx` (`Perfil_idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Administrador_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `mydb`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cobro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cobro` (
  `idCobro` INT NOT NULL,
  `NoTarjeta` INT NOT NULL,
  `Vencimiento` DATE NOT NULL,
  `Nombre` VARCHAR(70) NOT NULL,
  `Suscripcion_idSuscripcion` INT NOT NULL,
  PRIMARY KEY (`idCobro`),
  UNIQUE INDEX `NoTarjeta_UNIQUE` (`NoTarjeta` ASC) VISIBLE,
  INDEX `fk_Cobro_Suscripcion1_idx` (`Suscripcion_idSuscripcion` ASC) VISIBLE,
  CONSTRAINT `fk_Cobro_Suscripcion1`
    FOREIGN KEY (`Suscripcion_idSuscripcion`)
    REFERENCES `mydb`.`Suscripcion` (`idSuscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentarios` (
  `idComentarios` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Texto` MEDIUMTEXT NOT NULL,
  `Estado` TINYINT NOT NULL,
  PRIMARY KEY (`idComentarios`),
  UNIQUE INDEX `idComentarios_UNIQUE` (`idComentarios` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reportes` (
  `idReportes` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Articulos_idArticulos` INT NOT NULL,
  `Comentarios_idComentarios` INT NOT NULL,
  PRIMARY KEY (`idReportes`),
  UNIQUE INDEX `idReportes_UNIQUE` (`idReportes` ASC) VISIBLE,
  INDEX `fk_Reportes_Articulos1_idx` (`Articulos_idArticulos` ASC) VISIBLE,
  INDEX `fk_Reportes_Comentarios1_idx` (`Comentarios_idComentarios` ASC) VISIBLE,
  CONSTRAINT `fk_Reportes_Articulos1`
    FOREIGN KEY (`Articulos_idArticulos`)
    REFERENCES `mydb`.`Articulos` (`idArticulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reportes_Comentarios1`
    FOREIGN KEY (`Comentarios_idComentarios`)
    REFERENCES `mydb`.`Comentarios` (`idComentarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articulos_has_Moderado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articulos_has_Moderado` (
  `idArticuloM` INT NOT NULL,
  `idModeradorA` INT NOT NULL,
  PRIMARY KEY (`idArticuloM`, `idModeradorA`),
  INDEX `fk_Articulos_has_Moderado_Moderado1_idx` (`idModeradorA` ASC) VISIBLE,
  INDEX `fk_Articulos_has_Moderado_Articulos1_idx` (`idArticuloM` ASC) VISIBLE,
  CONSTRAINT `fk_Articulos_has_Moderado_Articulos1`
    FOREIGN KEY (`idArticuloM`)
    REFERENCES `mydb`.`Articulos` (`idArticulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articulos_has_Moderado_Moderado1`
    FOREIGN KEY (`idModeradorA`)
    REFERENCES `mydb`.`Moderado` (`idModerado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Moderado_has_Reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Moderado_has_Reportes` (
  `Moderado_idModerado` INT NOT NULL,
  `Reportes_idReportes` INT NOT NULL,
  PRIMARY KEY (`Moderado_idModerado`, `Reportes_idReportes`),
  INDEX `fk_Moderado_has_Reportes_Reportes1_idx` (`Reportes_idReportes` ASC) VISIBLE,
  INDEX `fk_Moderado_has_Reportes_Moderado1_idx` (`Moderado_idModerado` ASC) VISIBLE,
  CONSTRAINT `fk_Moderado_has_Reportes_Moderado1`
    FOREIGN KEY (`Moderado_idModerado`)
    REFERENCES `mydb`.`Moderado` (`idModerado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Moderado_has_Reportes_Reportes1`
    FOREIGN KEY (`Reportes_idReportes`)
    REFERENCES `mydb`.`Reportes` (`idReportes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
